//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lautech_Bank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lautechBankEntities1 : DbContext
    {
        public lautechBankEntities1()
            : base("name=lautechBankEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account_balance> Account_balance { get; set; }
        public DbSet<Account_Detail> Account_Detail { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<userdetail> userdetails { get; set; }
    }
}
