//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lautech_Bank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Transaction
    {
        public int id { get; set; }
        [Required(ErrorMessage="Select account type")]
        public string trans_type { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date_Time { get; set; }
        public long AccNo { get; set; }
    
        public virtual userdetail userdetail { get; set; }
    }
}
