//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lautech_Bank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class userdetail
    {
        public userdetail()
        {
            this.Account_balance = new HashSet<Account_balance>();
            this.Account_Detail = new HashSet<Account_Detail>();
            this.Transactions = new HashSet<Transaction>();
        }
        [Display(Name = "Id", AutoGenerateField = true)]
        public int Id { get; set; }
        [Display(Name = "Account Number", AutoGenerateField = true)]
        public long AccNo { get; set; }
        [Required(ErrorMessage = "Please enter your First name", AllowEmptyStrings = false)]
        [Display(Name = "First name")]
        public string fNmae { get; set; }
        [Required(ErrorMessage = "Please enter your Last name", AllowEmptyStrings = false)]
        [Display(Name = "Last name")]
        public string lName { get; set; }
        [Required(ErrorMessage = "Please enter your password", AllowEmptyStrings = false)]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        public virtual ICollection<Account_balance> Account_balance { get; set; }
        public virtual ICollection<Account_Detail> Account_Detail { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
